/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jobsity.test;

import jobsity.test.infrastructure.configuration.ScoringConfiguration;
import jobsity.test.scoring.ScoringEnvironment;
import jobsity.test.scoring.repositories.BowlingGameResultRepository;
import jobsity.test.scoring.repositories.BowlingGameResultRepositoryImpl;
import jobsity.test.scoring.repositories.ScoringRepositoryImpl;
import jobsity.test.scoring.services.ProcessGameResultFileServices;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
	    ScoringConfiguration config = new ScoringConfiguration();
	    ScoringRepositoryImpl scoringRepository = new ScoringRepositoryImpl();
	    BowlingGameResultRepository bowlingGameResultRepository = new BowlingGameResultRepositoryImpl(config.fileReaderConfiguration);


	    ScoringEnvironment environment = new ScoringEnvironment(config, scoringRepository, bowlingGameResultRepository);

	    new ProcessGameResultFileServices().run().apply(environment);

    }
}
